import { Eye, EyeOff, KeyRound, Save, ShieldCheck, Trash2, X, Zap } from "lucide-react";
import { useState } from "react";

import type { ApiStatus, AppSettings, MetadataMode } from "../../types";

interface SettingsPanelProps {
  settings: AppSettings;
  apiKeyConfigured: boolean;
  apiKeyVerified: boolean;
  offline: boolean;
  onSettingsChange: (settings: AppSettings) => void;
  onSaveApiKey: (value: string) => Promise<void>;
  onDeleteApiKey: () => Promise<void>;
  onTestApiKey: (value: string) => Promise<ApiStatus>;
  onClose: () => void;
}

export function SettingsPanel({ settings, apiKeyConfigured, apiKeyVerified, offline, onSettingsChange, onSaveApiKey, onDeleteApiKey, onTestApiKey, onClose }: SettingsPanelProps) {
  const [apiKey, setApiKey] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [status, setStatus] = useState<ApiStatus | undefined>();
  const [busy, setBusy] = useState(false);
  const update = (patch: Partial<AppSettings>) => onSettingsChange({ ...settings, ...patch });
  const test = async () => { setBusy(true); try { setStatus(await onTestApiKey(apiKey)); } catch (error) { setStatus({ connected: false, status: "failed", message: error instanceof Error ? error.message : String(error) }); } finally { setBusy(false); } };
  const save = async () => { if (!apiKey.trim()) return; setBusy(true); try { await onSaveApiKey(apiKey); setApiKey(""); setStatus({ connected: true, status: "connected", message: "API key saved securely." }); } catch (error) { setStatus({ connected: false, status: "failed", message: error instanceof Error ? error.message : String(error) }); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await onDeleteApiKey(); setStatus({ connected: false, status: "failed", message: "API key removed." }); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-40 flex justify-end bg-ink/20 backdrop-blur-[1px]" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <section className="flex h-full w-[470px] flex-col border-l border-line bg-[#fbfcfc] shadow-2xl" role="dialog" aria-modal="true" aria-label="Settings">
      <div className="flex h-[74px] items-center justify-between border-b border-line bg-white px-6"><div><p className="eyebrow">Application settings</p><h2 className="mt-1 text-[15px] font-bold text-ink">Preferences & connection</h2></div><button className="app-button app-button-quiet h-8 w-8 px-0" onClick={onClose} aria-label="Close settings"><X size={17} /></button></div>
      <div className="min-h-0 flex-1 overflow-y-auto p-6">
        {offline ? <div className="mb-5 rounded-md border border-amber-200 bg-amber-50 px-3 py-2.5 text-[11px] leading-4 text-amber-800"><b>Offline.</b> Existing metadata remains editable and exportable. AI generation requires an internet connection.</div> : null}
        <section><SectionTitle icon={<KeyRound size={14} />} title="AI connection" /><div className="mt-3 rounded-lg border border-line bg-white p-4"><label className="text-[11px] font-bold text-ink">Gemini API key</label><div className="relative mt-2"><input className="app-input pr-10" type={showKey ? "text" : "password"} value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={apiKeyConfigured ? "Saved securely in Stronghold" : "Paste your Gemini API key"} autoComplete="off" /><button className="absolute right-2 top-2 text-slate-400 hover:text-ink" onClick={() => setShowKey((value) => !value)} aria-label={showKey ? "Hide API key" : "Show API key"}>{showKey ? <EyeOff size={15} /> : <Eye size={15} />}</button></div><div className="mt-3 flex items-center justify-between"><span className={`flex items-center gap-1.5 text-[10px] font-semibold ${apiKeyVerified ? "text-mint" : "text-slate-400"}`}><ShieldCheck size={13} />{apiKeyVerified ? "Connected and verified" : apiKeyConfigured ? "Saved, connection not verified" : "No key configured"}</span><div className="flex gap-1.5"><button className="app-button h-8 px-2 text-[10px]" disabled={(!apiKey.trim() && !apiKeyConfigured) || busy || offline} onClick={test}>Test</button><button className="app-button app-button-primary h-8 px-2 text-[10px]" disabled={!apiKey.trim() || busy} onClick={save}><Save size={12} /> Save</button>{apiKeyConfigured ? <button className="app-button h-8 w-8 px-0 text-red-500 hover:border-red-200 hover:bg-red-50" disabled={busy} onClick={remove} aria-label="Delete API key"><Trash2 size={13} /></button> : null}</div></div>{status ? <p className={`mt-3 rounded-md px-2.5 py-2 text-[10px] leading-4 ${status.connected ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{status.message ?? (status.connected ? "Connected to Gemini." : "Connection failed.")}</p> : null}</div></section>
        <section className="mt-7"><SectionTitle icon={<Zap size={14} />} title="Generation" /><div className="mt-3 space-y-4 rounded-lg border border-line bg-white p-4"><Field label="AI model"><select className="app-input" value={settings.modelPreset} onChange={(event) => { const preset = event.target.value as AppSettings["modelPreset"]; update({ modelPreset: preset, model: preset === "balanced" ? "gemini-2.5-flash" : preset === "fast" ? "gemini-2.5-flash-lite" : settings.model }); }}><option value="balanced">Balanced · Gemini 2.5 Flash</option><option value="fast">Fast · Gemini 2.5 Flash Lite</option><option value="custom">Custom model ID</option></select></Field>{settings.modelPreset === "custom" ? <Field label="Custom model ID"><input className="app-input" value={settings.customModel} onChange={(event) => update({ customModel: event.target.value })} placeholder="gemini-2.5-flash" /></Field> : null}<div className="grid grid-cols-2 gap-3"><Field label="Batch size"><select className="app-input" value={settings.batchSize} onChange={(event) => update({ batchSize: Number(event.target.value) as AppSettings["batchSize"] })}>{[1, 2, 3, 4, 5, 6].map((value) => <option key={value} value={value}>{value} asset{value === 1 ? "" : "s"} per sheet</option>)}</select></Field><Field label="Concurrent requests"><select className="app-input" value={settings.concurrency} onChange={(event) => update({ concurrency: Number(event.target.value) as AppSettings["concurrency"] })}>{[1, 2, 3].map((value) => <option key={value} value={value}>{value} parallel</option>)}</select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Metadata style"><select className="app-input" value={settings.metadataMode} onChange={(event) => update({ metadataMode: event.target.value as MetadataMode })}><option value="strict">Strict</option><option value="balanced">Balanced</option><option value="discovery">Discovery</option></select></Field><Field label="Target keywords"><input className="app-input" type="number" min={30} max={45} value={settings.targetKeywords} onChange={(event) => update({ targetKeywords: Math.max(30, Math.min(45, Number(event.target.value))) })} /></Field></div></div></section>
        <section className="mt-7"><SectionTitle title="Image processing" /><div className="mt-3 space-y-4 rounded-lg border border-line bg-white p-4"><div><div className="flex justify-between text-[11px] font-semibold text-ink"><span>Contact sheet quality</span><span className="text-slate-400">{settings.contactSheetQuality}</span></div><input className="mt-2 w-full accent-accent" type="range" min={60} max={95} value={settings.contactSheetQuality} onChange={(event) => update({ contactSheetQuality: Number(event.target.value) })} /></div><Field label="Maximum sheet size"><select className="app-input" value={settings.maxSheetSize} onChange={(event) => update({ maxSheetSize: Number(event.target.value) })}><option value={1536}>1536 px</option><option value={2048}>2048 px</option><option value={2560}>2560 px</option></select></Field><Field label="Background"><select className="app-input" value={settings.background} onChange={(event) => update({ background: event.target.value as AppSettings["background"] })}><option value="neutral">Neutral</option><option value="white">White</option><option value="gray">Gray</option></select></Field></div></section>
        <section className="mt-7"><SectionTitle title="Export" /><div className="mt-3 rounded-lg border border-line bg-white p-4"><ToggleRow label="Include Releases column" value={settings.includeReleases} onChange={(value) => update({ includeReleases: value })} /><p className="mt-3 text-[10px] leading-4 text-slate-400">CSV is written with UTF-8 encoding and proper escaping. Large exports are split at 5,000 rows or approximately 1 MB.</p></div></section>
      </div>
      <div className="border-t border-line bg-white px-6 py-4"><p className="text-[10px] leading-4 text-slate-400">API keys are stored in Tauri Stronghold. Preferences use Tauri Store. Original image files are never modified.</p></div>
    </section>
  </div>;
}

function SectionTitle({ icon, title }: { icon?: React.ReactNode; title: string }) { return <div className="flex items-center gap-2 text-[12px] font-bold text-ink">{icon ? <span className="text-accent">{icon}</span> : null}{title}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</span>{children}</label>; }
function ToggleRow({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between"><span className="text-[11px] font-semibold text-ink">{label}</span><button className={`relative h-5 w-9 rounded-full transition ${value ? "bg-accent" : "bg-slate-300"}`} onClick={() => onChange(!value)} aria-pressed={value}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow transition ${value ? "left-[18px]" : "left-0.5"}`} /></button></div>; }
